// Tests for bump-version.mjs, run with `node --test scripts/bump-version.test.mjs`.
//
// The script resolves the repo root from its own location, so each test
// builds a miniature repo in a tmpdir, copies the script into its scripts/
// directory and runs it there — the real manifests are never touched.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { after, test } from "node:test";

const scriptSource = join(import.meta.dirname, "bump-version.mjs");
const trash = [];
after(() => {
	for (const dir of trash) rmSync(dir, { recursive: true, force: true });
});

const CARGO_TOML = (name) => `[package]
name = "${name}"
version = "1.2.3"
edition = "2021"
`;

const CARGO_LOCK = (name) => `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "${name}"
version = "1.2.3"

[[package]]
name = "serde"
version = "1.0.200"
`;

/** A miniature repo with every manifest the script rewrites. */
function makeFixture() {
	const root = mkdtempSync(join(tmpdir(), "bump-version-test-"));
	trash.push(root);
	const files = {
		"package.json": `${JSON.stringify({ name: "atomis", version: "1.2.3" }, null, 2)}\n`,
		"apps/web/package.json": `${JSON.stringify({ name: "@atomis/web", version: "1.2.3" }, null, 2)}\n`,
		"apps/desktop/package.json": `${JSON.stringify({ name: "@atomis/desktop", version: "1.2.3" }, null, 2)}\n`,
		"packages/protocol/package.json": `${JSON.stringify({ name: "@atomis/protocol", version: "1.2.3" }, null, 2)}\n`,
		"apps/desktop/src-tauri/tauri.conf.json": `${JSON.stringify({ version: "1.2.3" }, null, 2)}\n`,
		"apps/server-rs/Cargo.toml": CARGO_TOML("atomis-server"),
		"apps/server-rs/Cargo.lock": CARGO_LOCK("atomis-server"),
		"apps/desktop/src-tauri/Cargo.toml": CARGO_TOML("app"),
		"apps/desktop/src-tauri/Cargo.lock": CARGO_LOCK("app"),
	};
	for (const [path, content] of Object.entries(files)) {
		mkdirSync(join(root, dirname(path)), { recursive: true });
		writeFileSync(join(root, path), content);
	}
	mkdirSync(join(root, "scripts"));
	cpSync(scriptSource, join(root, "scripts/bump-version.mjs"));
	return root;
}

function bump(root, request) {
	return spawnSync(
		process.execPath,
		[join(root, "scripts/bump-version.mjs"), request],
		{ encoding: "utf8" },
	);
}

test("a patch bump rewrites every manifest and both sides of each cargo pair", () => {
	const root = makeFixture();
	const result = bump(root, "patch");
	assert.equal(result.status, 0, result.stderr);
	assert.equal(result.stdout.trim().split("\n").at(-1), "1.2.4");

	for (const file of [
		"package.json",
		"apps/web/package.json",
		"apps/desktop/package.json",
		"packages/protocol/package.json",
		"apps/desktop/src-tauri/tauri.conf.json",
	]) {
		const parsed = JSON.parse(readFileSync(join(root, file), "utf8"));
		assert.equal(parsed.version, "1.2.4", file);
	}
	for (const [toml, lock, name] of [
		["apps/server-rs/Cargo.toml", "apps/server-rs/Cargo.lock", "atomis-server"],
		["apps/desktop/src-tauri/Cargo.toml", "apps/desktop/src-tauri/Cargo.lock", "app"],
	]) {
		assert.match(readFileSync(join(root, toml), "utf8"), /^version = "1\.2\.4"$/m, toml);
		assert.match(
			readFileSync(join(root, lock), "utf8"),
			new RegExp(`name = "${name}"\\nversion = "1\\.2\\.4"`),
			lock,
		);
		// The unrelated lock entry is left alone.
		assert.match(readFileSync(join(root, lock), "utf8"), /name = "serde"\nversion = "1\.0\.200"/, lock);
	}
});

test("a Cargo.lock without the package entry fails instead of pretending", () => {
	const root = makeFixture();
	// The entry the script must find is missing: same shape, wrong name.
	writeFileSync(
		join(root, "apps/server-rs/Cargo.lock"),
		CARGO_LOCK("something-else"),
	);
	const result = bump(root, "patch");
	assert.equal(result.status, 1);
	assert.match(result.stderr, /no package entry for atomis-server/);
});

test("a Cargo.toml without a version line still fails as before", () => {
	const root = makeFixture();
	writeFileSync(
		join(root, "apps/server-rs/Cargo.toml"),
		'[package]\nname = "atomis-server"\n',
	);
	const result = bump(root, "patch");
	assert.equal(result.status, 1);
	assert.match(result.stderr, /no version line/);
});
