import type * as Monaco from "monaco-editor";

export const goMonarch: Monaco.languages.IMonarchLanguage = {
	defaultToken: "",
	tokenPostfix: ".go",
	keywords: [
		"break",
		"case",
		"chan",
		"const",
		"continue",
		"default",
		"defer",
		"else",
		"fallthrough",
		"for",
		"func",
		"go",
		"goto",
		"if",
		"import",
		"interface",
		"map",
		"package",
		"range",
		"return",
		"select",
		"struct",
		"switch",
		"type",
		"var",
		"nil",
		"true",
		"false",
		"iota",
	],
	typeKeywords: [
		"bool",
		"byte",
		"complex64",
		"complex128",
		"error",
		"float32",
		"float64",
		"int",
		"int8",
		"int16",
		"int32",
		"int64",
		"rune",
		"string",
		"uint",
		"uint8",
		"uint16",
		"uint32",
		"uint64",
		"uintptr",
		"any",
	],
	operators: [
		"=",
		">",
		"<",
		"!",
		"~",
		"?",
		":",
		"==",
		"<=",
		">=",
		"!=",
		"&&",
		"||",
		"++",
		"--",
		"+",
		"-",
		"*",
		"/",
		"&",
		"|",
		"^",
		"%",
		"<<",
		">>",
		"+=",
		"-=",
		"*=",
		"/=",
		":=",
		"<-",
		"...",
	],
	tokenizer: {
		root: [
			[/\/\/.*/, "comment"],
			[/\/\*/, "comment", "@blockComment"],
			[/`/, { token: "string.quote", bracket: "@open", next: "@rawstring" }],
			[/"/, { token: "string.quote", bracket: "@open", next: "@string" }],
			[/'([^'\\]|\\.)'/, "string"],
			[
				/[A-Za-z_]\w*/,
				{
					cases: {
						"@keywords": "keyword",
						"@typeKeywords": "type",
						"@default": "identifier",
					},
				},
			],
			[/0[xX][0-9a-fA-F](_?[0-9a-fA-F])*/, "number.hex"],
			[/0[bB][01](_?[01])*/, "number.binary"],
			[/0[oO]?[0-7](_?[0-7])*/, "number.octal"],
			[/(\d[\d_]*\.?[\d_]*|\.\d[\d_]*)([eE][+-]?[\d_]+)?i?/, "number"],
			[/[{}()[\]]/, "@brackets"],
			[/[;,.]/, "delimiter"],
			[/[=><!~?:&|+\-*/%^]+/, "operator"],
		],
		blockComment: [
			[/[^/*]+/, "comment"],
			[/\*\//, "comment", "@pop"],
			[/[/*]/, "comment"],
		],
		string: [
			[/[^\\"]+/, "string"],
			[/\\(x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8}|.)/, "string.escape"],
			[/"/, { token: "string.quote", bracket: "@close", next: "@pop" }],
		],
		rawstring: [
			[/[^`]+/, "string"],
			[/`/, { token: "string.quote", bracket: "@close", next: "@pop" }],
		],
	},
};

export function registerGo(monaco: typeof Monaco): void {
	monaco.languages.register({
		id: "go",
		extensions: [".go"],
		aliases: ["Go", "golang"],
	});
	monaco.languages.setMonarchTokensProvider("go", goMonarch);
	monaco.languages.setLanguageConfiguration("go", {
		comments: { lineComment: "//", blockComment: ["/*", "*/"] },
		brackets: [
			["{", "}"],
			["[", "]"],
			["(", ")"],
		],
		autoClosingPairs: [
			{ open: "{", close: "}" },
			{ open: "[", close: "]" },
			{ open: "(", close: ")" },
			{ open: '"', close: '"' },
			{ open: "`", close: "`" },
		],
	});
}
