import type * as Monaco from "monaco-editor";

export const pyMonarch: Monaco.languages.IMonarchLanguage = {
	defaultToken: "",
	tokenPostfix: ".python",
	keywords: [
		"and",
		"as",
		"assert",
		"async",
		"await",
		"break",
		"class",
		"continue",
		"def",
		"del",
		"elif",
		"else",
		"except",
		"False",
		"finally",
		"for",
		"from",
		"global",
		"if",
		"import",
		"in",
		"is",
		"lambda",
		"match",
		"None",
		"nonlocal",
		"not",
		"or",
		"pass",
		"raise",
		"return",
		"True",
		"try",
		"while",
		"with",
		"yield",
	],
	typeKeywords: [
		"bool",
		"bytes",
		"complex",
		"dict",
		"float",
		"frozenset",
		"int",
		"list",
		"object",
		"set",
		"str",
		"tuple",
		"type",
	],
	operators: [
		"=",
		">",
		"<",
		"!",
		"~",
		"?",
		":",
		"==",
		"<=",
		">=",
		"!=",
		"+",
		"-",
		"*",
		"**",
		"/",
		"//",
		"&",
		"|",
		"^",
		"%",
		"<<",
		">>",
		"+=",
		"-=",
		"*=",
		"/=",
		":=",
		"->",
	],
	tokenizer: {
		root: [
			[/#.*/, "comment"],
			[/@[A-Za-z_][\w.]*/, "predefined"],
			[
				/[rRbBuUfF]{0,2}"""/,
				{ token: "string.quote", bracket: "@open", next: "@tdstring" },
			],
			[
				/[rRbBuUfF]{0,2}'''/,
				{ token: "string.quote", bracket: "@open", next: "@tsstring" },
			],
			[
				/[rRbBuUfF]{0,2}"/,
				{ token: "string.quote", bracket: "@open", next: "@dstring" },
			],
			[
				/[rRbBuUfF]{0,2}'/,
				{ token: "string.quote", bracket: "@open", next: "@sstring" },
			],
			[
				/[A-Za-z_]\w*/,
				{
					cases: {
						"@keywords": "keyword",
						"@typeKeywords": "type",
						"@default": "identifier",
					},
				},
			],
			[/0[xX][0-9a-fA-F](_?[0-9a-fA-F])*/, "number.hex"],
			[/0[bB][01](_?[01])*/, "number.binary"],
			[/0[oO][0-7](_?[0-7])*/, "number.octal"],
			[/(\d[\d_]*\.?[\d_]*|\.\d[\d_]*)([eE][+-]?[\d_]+)?[jJ]?/, "number"],
			[/[{}()[\]]/, "@brackets"],
			[/[;,.]/, "delimiter"],
			[/[=><!~?:&|+\-*/%^]+/, "operator"],
		],
		dstring: [
			[/[^\\"]+/, "string"],
			[/\\./, "string.escape"],
			[/"/, { token: "string.quote", bracket: "@close", next: "@pop" }],
		],
		sstring: [
			[/[^\\']+/, "string"],
			[/\\./, "string.escape"],
			[/'/, { token: "string.quote", bracket: "@close", next: "@pop" }],
		],
		tdstring: [
			[/[^\\"]+/, "string"],
			[/\\./, "string.escape"],
			[/"""/, { token: "string.quote", bracket: "@close", next: "@pop" }],
			[/"/, "string"],
		],
		tsstring: [
			[/[^\\']+/, "string"],
			[/\\./, "string.escape"],
			[/'''/, { token: "string.quote", bracket: "@close", next: "@pop" }],
			[/'/, "string"],
		],
	},
};

export function registerPy(monaco: typeof Monaco): void {
	monaco.languages.register({
		id: "python",
		extensions: [".py"],
		aliases: ["Python", "python"],
	});
	monaco.languages.setMonarchTokensProvider("python", pyMonarch);
	monaco.languages.setLanguageConfiguration("python", {
		comments: { lineComment: "#" },
		brackets: [
			["{", "}"],
			["[", "]"],
			["(", ")"],
		],
		autoClosingPairs: [
			{ open: "{", close: "}" },
			{ open: "[", close: "]" },
			{ open: "(", close: ")" },
			{ open: '"', close: '"' },
			{ open: "'", close: "'" },
		],
		onEnterRules: [
			{
				beforeText: /:\s*$/,
				action: { indentAction: monaco.languages.IndentAction.Indent },
			},
		],
	});
}
