import type * as Monaco from "monaco-editor";

export const tsMonarch: Monaco.languages.IMonarchLanguage = {
	defaultToken: "",
	tokenPostfix: ".ts",
	keywords: [
		"abstract",
		"as",
		"async",
		"await",
		"break",
		"case",
		"catch",
		"class",
		"const",
		"continue",
		"debugger",
		"default",
		"delete",
		"do",
		"else",
		"enum",
		"export",
		"extends",
		"false",
		"finally",
		"for",
		"from",
		"function",
		"get",
		"if",
		"implements",
		"import",
		"in",
		"instanceof",
		"interface",
		"is",
		"keyof",
		"let",
		"namespace",
		"new",
		"null",
		"of",
		"private",
		"protected",
		"public",
		"readonly",
		"return",
		"satisfies",
		"set",
		"static",
		"super",
		"switch",
		"this",
		"throw",
		"true",
		"try",
		"type",
		"typeof",
		"undefined",
		"var",
		"void",
		"while",
		"yield",
	],
	typeKeywords: [
		"any",
		"bigint",
		"boolean",
		"never",
		"number",
		"object",
		"string",
		"symbol",
		"unknown",
	],
	operators: [
		"=",
		">",
		"<",
		"!",
		"~",
		"?",
		":",
		"==",
		"===",
		"!=",
		"!==",
		"<=",
		">=",
		"&&",
		"||",
		"??",
		"++",
		"--",
		"+",
		"-",
		"*",
		"**",
		"/",
		"&",
		"|",
		"^",
		"%",
		"<<",
		">>",
		">>>",
		"+=",
		"-=",
		"*=",
		"/=",
		"=>",
		"...",
	],
	tokenizer: {
		root: [
			[/\/\/.*/, "comment"],
			[/\/\*/, "comment", "@blockComment"],
			[/`/, { token: "string.quote", bracket: "@open", next: "@template" }],
			[/"/, { token: "string.quote", bracket: "@open", next: "@dstring" }],
			[/'/, { token: "string.quote", bracket: "@open", next: "@sstring" }],
			[/@[A-Za-z_][\w]*/, "predefined"],
			[
				/[A-Za-z_$][\w$]*/,
				{
					cases: {
						"@keywords": "keyword",
						"@typeKeywords": "type",
						"@default": "identifier",
					},
				},
			],
			[/0[xX][0-9a-fA-F](_?[0-9a-fA-F])*n?/, "number.hex"],
			[/0[bB][01](_?[01])*n?/, "number.binary"],
			[/0[oO][0-7](_?[0-7])*n?/, "number.octal"],
			[/(\d[\d_]*\.?[\d_]*|\.\d[\d_]*)([eE][+-]?[\d_]+)?n?/, "number"],
			[/[{}()[\]]/, "@brackets"],
			[/[;,.]/, "delimiter"],
			[/[=><!~?:&|+\-*/%^]+/, "operator"],
		],
		blockComment: [
			[/[^/*]+/, "comment"],
			[/\*\//, "comment", "@pop"],
			[/[/*]/, "comment"],
		],
		dstring: [
			[/[^\\"]+/, "string"],
			[/\\./, "string.escape"],
			[/"/, { token: "string.quote", bracket: "@close", next: "@pop" }],
		],
		sstring: [
			[/[^\\']+/, "string"],
			[/\\./, "string.escape"],
			[/'/, { token: "string.quote", bracket: "@close", next: "@pop" }],
		],
		template: [
			[/[^\\`$]+/, "string"],
			[/\$\{/, { token: "string.escape", next: "@templateExpr" }],
			[/\\./, "string.escape"],
			[/`/, { token: "string.quote", bracket: "@close", next: "@pop" }],
		],
		templateExpr: [
			[/[^}]+/, "identifier"],
			[/\}/, { token: "string.escape", next: "@pop" }],
		],
	},
};

export function registerTs(monaco: typeof Monaco): void {
	for (const [id, extensions] of [
		["typescript", [".ts"]],
		["javascript", [".js", ".mjs", ".cjs"]],
	] as const) {
		monaco.languages.register({ id, extensions: [...extensions] });
		monaco.languages.setMonarchTokensProvider(id, tsMonarch);
		monaco.languages.setLanguageConfiguration(id, {
			comments: { lineComment: "//", blockComment: ["/*", "*/"] },
			brackets: [
				["{", "}"],
				["[", "]"],
				["(", ")"],
			],
			autoClosingPairs: [
				{ open: "{", close: "}" },
				{ open: "[", close: "]" },
				{ open: "(", close: ")" },
				{ open: '"', close: '"' },
				{ open: "'", close: "'" },
				{ open: "`", close: "`" },
			],
		});
	}
}
