import type * as Monaco from "monaco-editor";

export const zigMonarch: Monaco.languages.IMonarchLanguage = {
	defaultToken: "",
	tokenPostfix: ".zig",
	keywords: [
		"addrspace",
		"align",
		"allowzero",
		"and",
		"anyframe",
		"anytype",
		"asm",
		"async",
		"await",
		"break",
		"callconv",
		"catch",
		"comptime",
		"const",
		"continue",
		"defer",
		"else",
		"enum",
		"errdefer",
		"error",
		"export",
		"extern",
		"fn",
		"for",
		"if",
		"inline",
		"noalias",
		"nosuspend",
		"opaque",
		"or",
		"orelse",
		"packed",
		"pub",
		"resume",
		"return",
		"struct",
		"suspend",
		"switch",
		"test",
		"threadlocal",
		"try",
		"union",
		"unreachable",
		"usingnamespace",
		"var",
		"volatile",
		"while",
	],
	typeKeywords: [
		"bool",
		"void",
		"noreturn",
		"type",
		"anyerror",
		"anyopaque",
		"usize",
		"isize",
		"comptime_int",
		"comptime_float",
		"f16",
		"f32",
		"f64",
		"f80",
		"f128",
		"i8",
		"i16",
		"i32",
		"i64",
		"i128",
		"u8",
		"u16",
		"u32",
		"u64",
		"u128",
	],
	operators: [
		"=",
		">",
		"<",
		"!",
		"~",
		"?",
		":",
		"==",
		"<=",
		">=",
		"!=",
		"&&",
		"||",
		"++",
		"+",
		"-",
		"*",
		"/",
		"&",
		"|",
		"^",
		"%",
		"<<",
		">>",
		"+=",
		"-=",
		"*=",
		"/=",
	],
	tokenizer: {
		root: [
			[/\/\/\/.*/, "comment.doc"],
			[/\/\/.*/, "comment"],
			[/c?"/, { token: "string.quote", bracket: "@open", next: "@string" }],
			[/'([^'\\]|\\.)'/, "string"],
			[/@[A-Za-z_][\w]*/, "predefined"],
			[
				/[A-Za-z_]\w*/,
				{
					cases: {
						"@keywords": "keyword",
						"@typeKeywords": "type",
						"@default": "identifier",
					},
				},
			],
			[/0[xX][0-9a-fA-F](_?[0-9a-fA-F])*/, "number.hex"],
			[/0[bB][01](_?[01])*/, "number.binary"],
			[/(\d[\d_]*\.?[\d_]*|\.\d[\d_]*)([eEpP][+-]?[\d_]+)?/, "number"],
			[/[{}()[\]]/, "@brackets"],
			[/[;,.]/, "delimiter"],
			[/[=><!~?:&|+\-*/%^]+/, "operator"],
		],
		string: [
			[/[^\\"]+/, "string"],
			[/\\(x[0-9A-Fa-f]{2}|u\{[0-9A-Fa-f]+\}|.)/, "string.escape"],
			[/"/, { token: "string.quote", bracket: "@close", next: "@pop" }],
		],
	},
};

const mochaRules: Monaco.editor.ITokenThemeRule[] = [
	{ token: "keyword", foreground: "cba6f7", fontStyle: "bold" },
	{ token: "type", foreground: "f9e2af" },
	{ token: "predefined", foreground: "fab387" },
	{ token: "string", foreground: "a6e3a1" },
	{ token: "string.escape", foreground: "f5c2e7" },
	{ token: "number", foreground: "fab387" },
	{ token: "comment", foreground: "6c7086", fontStyle: "italic" },
	{ token: "comment.doc", foreground: "7f849c", fontStyle: "italic" },
	{ token: "operator", foreground: "89dceb" },
];

function mochaColors(background: string): Record<string, string> {
	return {
		"editor.background": background,
		"editor.foreground": "#cdd6f4",
		"editorCursor.foreground": "#cba6f7",
		"editorLineNumber.foreground": "#585b70",
		"editorLineNumber.activeForeground": "#cdd6f4",
		"editor.selectionBackground": "#45475a",
		"editor.inactiveSelectionBackground": "#313244",
		"editorIndentGuide.background1": "#313244",
		"editorIndentGuide.activeBackground1": "#45475a",
		"editorWhitespace.foreground": "#313244",
		"editorError.foreground": "#f38ba8",
		"editorWarning.foreground": "#f9e2af",
		"editorInfo.foreground": "#89b4fa",
		"editorOverviewRuler.border": "#00000000",
		"editorSuggestWidget.background": "#181825",
		"editorSuggestWidget.border": "#313244",
		"editorSuggestWidget.foreground": "#cdd6f4",
		"editorSuggestWidget.selectedBackground": "#313244",
		"editorSuggestWidget.selectedForeground": "#fab387",
		"editorSuggestWidget.selectedIconForeground": "#fab387",
		"editorSuggestWidget.highlightForeground": "#cba6f7",
		"editorSuggestWidget.focusHighlightForeground": "#fab387",
		"editorSuggestWidgetStatus.foreground": "#6c7086",
		"symbolIcon.functionForeground": "#89b4fa",
		"symbolIcon.methodForeground": "#89b4fa",
		"symbolIcon.constructorForeground": "#89b4fa",
		"symbolIcon.classForeground": "#f9e2af",
		"symbolIcon.structForeground": "#f9e2af",
		"symbolIcon.interfaceForeground": "#f9e2af",
		"symbolIcon.moduleForeground": "#f9e2af",
		"symbolIcon.namespaceForeground": "#f9e2af",
		"symbolIcon.enumeratorForeground": "#f9e2af",
		"symbolIcon.enumeratorMemberForeground": "#94e2d5",
		"symbolIcon.variableForeground": "#cdd6f4",
		"symbolIcon.fieldForeground": "#94e2d5",
		"symbolIcon.propertyForeground": "#94e2d5",
		"symbolIcon.constantForeground": "#fab387",
		"symbolIcon.keywordForeground": "#cba6f7",
		"symbolIcon.snippetForeground": "#a6e3a1",
		"symbolIcon.textForeground": "#a6adc8",
		"symbolIcon.fileForeground": "#a6adc8",
		"symbolIcon.folderForeground": "#a6adc8",
		"symbolIcon.typeParameterForeground": "#f9e2af",
		"symbolIcon.operatorForeground": "#94e2d5",
		"symbolIcon.referenceForeground": "#a6adc8",
		"symbolIcon.unitForeground": "#fab387",
		"symbolIcon.valueForeground": "#fab387",
		"symbolIcon.eventForeground": "#fab387",
		"editorHoverWidget.background": "#181825",
		"editorHoverWidget.border": "#313244",
		"editorGutter.background": background,
		"scrollbarSlider.background": "#31324488",
		"scrollbarSlider.hoverBackground": "#45475a88",
		"scrollbarSlider.activeBackground": "#45475aaa",
	};
}

export function registerZig(monaco: typeof Monaco): void {
	monaco.editor.defineTheme("atomis-dark", {
		base: "vs-dark",
		inherit: true,
		rules: mochaRules,
		colors: mochaColors("#1e1e2e"),
	});
	monaco.editor.defineTheme("atomis-zen", {
		base: "vs-dark",
		inherit: true,
		rules: mochaRules,
		colors: mochaColors("#181825"),
	});
	monaco.languages.register({
		id: "zig",
		extensions: [".zig"],
		aliases: ["Zig", "zig"],
	});
	monaco.languages.setMonarchTokensProvider("zig", zigMonarch);
	monaco.languages.setLanguageConfiguration("zig", {
		comments: { lineComment: "//", blockComment: ["/*", "*/"] },
		brackets: [
			["{", "}"],
			["[", "]"],
			["(", ")"],
		],
		autoClosingPairs: [
			{ open: "{", close: "}" },
			{ open: "[", close: "]" },
			{ open: "(", close: ")" },
			{ open: '"', close: '"' },
			{ open: "'", close: "'" },
		],
	});
}
